#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

# Create REANA DB
echo 'Creating REANA database ...'
invenio reana-db init
invenio reana-users create_default info@reana.io  > /dev/null 2>&1

# Create Invenio DB
echo 'Creating Invenio database ...'
invenio db init
invenio db create

# Create admin role to rectict access
invenio roles create admin || echo "Admin role already exists"
invenio access allow superuser-access role admin || echo "Admin role already has superuser-access"
